# Generated by Django 5.0.6 on 2024-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('Model_Description', models.CharField(max_length=100)),
                ('Processor', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=20)),
                ('Storage', models.CharField(max_length=50)),
                ('Display', models.CharField(max_length=50)),
                ('OS', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
